// scripts/vault/index-drift.mjs
import { domainsOf } from "./node-row.mjs";

// HARD: every node id must appear in the generated by-type region.
export function coverageGaps(nodes, byTypeBody) {
  const gaps = [];
  for (const n of nodes) {
    if (!byTypeBody.includes(`[[${n.id}]]`)) gaps.push(`node ${n.id} is missing from index-by-type (run /vault-map)`);
  }
  return gaps;
}

// HARD: a domain index file whose domain has zero member nodes is orphaned.
export function orphanedDomainIndexes(nodes, domainIndexIds) {
  const populated = new Set();
  for (const n of nodes) for (const d of domainsOf(n)) populated.add(`index-domain-${d}`);
  return domainIndexIds.filter((id) => !populated.has(id));
}

// HARD: a populated domain with no index file (missing sub-index).
export function missingDomainIndexes(nodes, domainIndexIds) {
  const have = new Set(domainIndexIds);
  const missing = [];
  const populated = new Set();
  for (const n of nodes) for (const d of domainsOf(n)) populated.add(d);
  for (const d of populated) if (!have.has(`index-domain-${d}`)) missing.push(`domain ${d} has nodes but no index-domain-${d}.md (run /vault-map)`);
  return missing;
}
